# Generated by Django 5.0.4 on 2024-06-21 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0012_bloodhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodhistory',
            name='action',
            field=models.CharField(choices=[('add', 'Add'), ('increase', 'Increase'), ('decrease', 'Decrease')], default='add', max_length=10),
        ),
    ]
